const citydata = [

    {name: "New York", description: "New York mit nur einem Besuch erobern? Unmöglich. Sie sollten aber auf jeden Fall die Freiheitsstatue, das Empire State Building, den Central Park und das Metropolitan Museum of Art besuchen. Aber auch weniger berühmte Sehenswürdigkeiten wie The Cloisters oder eine der Bibliotheken sind immer einen Besuch wert. Verwöhnen Sie sich in den unkonventionellen Geschäften des West Village oder in einem gehobenen Restaurant der Upper West Side. Auf dem pulsierenden Markt im Innern der Grand Central Station erhalten Sie buchstäblich eine Kostprobe vom Besten, das die Stadt zu bieten hat."},

    {name: "London", description: "London ist ein Mix aus vielen Kulturen und Lebensstilen, vom hippen Shoreditch-Viertel über das punkige Camden bis zur schicken Portobello Road. Diese energiegeladene Stadt erfindet sich jeden Tag neu. Erkunden Sie historische oder royale Stätten und Sehenswürdigkeiten, die auf Ihrer Wunschliste ganz oben stehen."},

    {name: "Paris", description: "Ein Pain au Chocolat in einem kleinen Straßencafé genießen, nach einem Tag an der Seine und dem Bestaunen der Touristenattraktionen wie dem Eiffelturm oder dem Arc de Triomphe ein wenig entspannen – in Paris verbindet ein perfektes Erlebnis stets Vergnügen und Lebhaftigkeit mit ausreichend Zeit, um sowohl ein exquisites Essen als auch eine Ausstellung im Louvre auszukosten. Beleben Sie Ihren Geist in der Notre Dame, machen Sie ein Schnäppchen auf dem Marché aux Puces de Montreuil oder entdecken Sie die Leckereien auf dem Marché biologique Raspail und lassen Sie sich zur Krönung von einer spektakulären Vorstellung im Moulin Rouge begeistern."},

    {name: "Berlin", description: "Berlin ist wahrhaft eine einzigartige Stadt, von ihrer Mode über die Architektur bis hin zu ihrer einmaligen politischen Geschichte. Die Berliner Mauer erinnert auf ernüchternde Weise an die äußerst angespannte Nachkriegszeit, doch die Graffiti-Werke, die heute die Überreste der Grenzanlagen zieren, wurden zum Symbol des sozialen Fortschritts. Statten Sie der Weltzeituhr einen Besuch ab, über der sich eine Nachbildung des Sonnensystems befindet. Anschließend drehen Sie ein wenig die Zeit zurück und genießen ein Essen in der historischen Gaststätte Zur letzten Instanz, ein Restaurant aus dem 16. Jahrhundert, das regelmäßig von Napoleon und Beethoven besucht wurde."}

]

export default citydata